Shambala/urls.py
from django.contrib import admin
from django.urls import path,include
from measures import views
from todo import views1
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('user/', include("user.urls")),
    path('measures/',include("measures.urls")),
    path('todos/',include("todo.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

measures/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "measures"

urlpatterns = [
    path('', views.index, name="index"),
    path('analyze/', views.analyze, name="analyze"),   
    path('measures/', views.set_measure_names, name="measures"),   

]

todo/urls.py
from django.contrib import admin
from django.urls import path
from . import views1

app_name = "todo"

urlpatterns = [
    path('', views1.todos, name="todos"),
    path('update/<int:id>', views1.updatetodo, name="updatetodo"),   
    path('delete/<int:id>', views1.deletetodo, name="deletetodo"),   
    path('add/', views1.addtodo, name="addtodo"),   

]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ProfileListView

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),   
    path('profile/', views.view_profile, name="profile"),   
    path('update_profile/<int:id>', views.update_profile, name="update_profile"),
    path('public_profile/<int:id>', views.public_profile, name="public_profile"),
    path('update_image/<int:id>', views.update_image, name="update_image"),
    path('friends/', views.friends_invites, name="friends"),
    #path('allprofiles/', views.allprofiles, name="allprofiles"),
    path("allprofiles/", ProfileListView.as_view(), name="allprofiles"),
    path('inviteprofiles/', views.inviteprofiles, name="inviteprofiles"),
    path("send-invite/", views.send_invitation, name="send-invite"),
    path("remove-friend/",views.remove_from_friends, name="remove-friend"),
    path("accept-invitation/",views.accept_invitation, name="accept-invitation"),
    path("reject-invitation/",views.reject_invitation, name="reject-invitation"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/navbar.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    <link rel="stylesheet" type="text/css" href="/static/css/navbar.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <title>Shambala's Gates</title>
</head>

<nav>
    <div class="row header-row">
        <ul class="main-nav left js--main-nav">
            <li class="shambala"><a  href="{% url 'index'  %}">Shambala's Gates</a></li>
            {% if request.user.is_authenticated %}
            <li class="measures"><a href="{% url 'measures:measures'  %}">Measures</a></li>
            <li class="analyze"><a href="{% url 'measures:analyze'  %}">Analyze</a></li>
            <li class="todos"><a href="{% url 'todo:todos' %}">To-do's</a></li>

            {% endif %}
        </ul>
        {% if request.user.is_authenticated %}
        <ul class="main-nav right js--main-nav">
            <li><a href="{% url 'user:logout'  %}">Logout</a></li>
            <li><a href="{% url 'user:register'  %}">Register</a></li>
            <li><a href="{% url 'user:profile'  %}">Profile</a></li>
            <li><a href="{% url 'user:allprofiles'  %}">Friends</a></li>

<!--
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Friends
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" style="background-color:#3e0c67 ; color: white; padding: 0px !important;" href="{% url 'user:friends'  %}">My Friends</a>
                  <a class="dropdown-item" style="background-color:#3e0c67 ; color: white;padding: 0px !important;" href="{% url 'user:allprofiles'  %}">All Users</a>
                </div>
              </li>


                <li><a href="{% url 'user:friends'  %}">Friends</a></li>
                <li><a href="{% url 'user:allprofiles'  %}">All Profiles</a></li>
                <li><a href="{% url 'user:inviteprofiles'  %}">Profiles to Invite</a></li>
-->
                
        </ul>
        {% else %}
        <ul class="main-nav right js--main-nav">
            <li><a href="{% url 'user:login'  %}">Login</a></li>
            <li><a href="{% url 'user:register'  %}">Register</a></li>
        </ul>
        {% endif %}

    </div>
</nav>