Shambala/urls.py
from django.contrib import admin
from django.urls import path,include
from measures import views
from todo import views1
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('user/', include("user.urls")),
    path('measures/',include("measures.urls")),
    path('todos/',include("todo.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.contrib import admin
from django.urls import path
from . import views1

app_name = "todo"

urlpatterns = [
    path('', views1.todos, name="todos"),
    path('update/<int:id>', views1.updatetodo, name="updatetodo"),   
    path('delete/<int:id>', views1.deletetodo, name="deletetodo"),   
    path('add/', views1.addtodo, name="addtodo"),   

]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ProfileListView

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),   
    path('profile/', views.view_profile, name="profile"),   
    path('update_profile/<int:id>', views.update_profile, name="update_profile"),
    path('public_profile/<int:id>', views.public_profile, name="public_profile"),
    path('update_image/<int:id>', views.update_image, name="update_image"),
    path('friends/', views.friends_invites, name="friends"),
    #path('allprofiles/', views.allprofiles, name="allprofiles"),
    path("allprofiles/", ProfileListView.as_view(), name="allprofiles"),
    path('inviteprofiles/', views.inviteprofiles, name="inviteprofiles"),
    path("send-invite/", views.send_invitation, name="send-invite"),
    path("remove-friend/",views.remove_from_friends, name="remove-friend"),
    path("accept-invitation/",views.accept_invitation, name="accept-invitation"),
    path("reject-invitation/",views.reject_invitation, name="reject-invitation"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/models.py
from django.db import models

class todo(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name= "Author")
    title = models.CharField(max_length = 50,verbose_name = "title")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="todo date")
    def __str__(self): 
        return '%s - %s' % (self.author, self.title)
    class Meta:
        ordering = ['-created_date']

todo/forms.py
from django import forms
from .models import todo

class todoform(forms.ModelForm):
    class Meta:
        model = todo
        fields = ['title']

user/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username"] 
       
class ImageUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]


class LoginForm(forms.Form):
    username = forms.CharField(label = "Username")
    password = forms.CharField(label = "Password", widget = forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Username")
    password = forms.CharField(max_length=20,label = "Password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Confirm Password",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords don't match")

        values = {
            "username" : username,
            "password" : password
        }
        return values



class interests_form(forms.ModelForm):
    interests = forms.CharField(label="")
    class Meta:
        model = Profile
        fields = ["interests"]

class youtube_form(forms.ModelForm):
    youtube_id = forms.CharField(label ="")
    class Meta:
        model = Profile
        fields = ['youtube_id']  

class instagram_form(forms.ModelForm):
    instagram_id = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['instagram_id']   
    
class twitter_form(forms.ModelForm):    
    twitter_id = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['twitter_id'] 

class facebook_form(forms.ModelForm):
    facebook_id = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['facebook_id']

class spotify_form(forms.ModelForm):
    spotify_id = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['spotify_id'] 

class soundcloud_form(forms.ModelForm):
    soundcloud_id = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['soundcloud_id'] 

class phone_form(forms.ModelForm):
    phone = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['phone'] 

class email_form(forms.ModelForm):
    email = forms.CharField(label = "")
    class Meta:
        model = Profile
        fields = ['email'] 

templates/allprofiles.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}





<div class="">





 <!------------------ 1.  FRIEND REQUESTs ------------------------>


 <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
 background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
 width: 40%; height: fit-content; margin:5px 30%;">
 <h4>
     <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
     {% if request.user.is_authenticated %}
     Friend Requests for <span style="color: gold;">{{request.user.username}}</span> 

     {% else %}
    
     {% endif %}

     </span>
 </h4>
</div>


 <div class="links_container">
    {% for obj in object_list %}
    {% if obj.user in rel_sender  and  request.user not in obj.friends.all %}            

    <div class="profile_line_all_profiles">
        <!--PROFILE IMAGE-->
        <div  style="display: inline-block;">
            <img class="social_icon" src="{{obj.image.url}}">
        </div>

        <!--PROFILE NAME AND LINK-->
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a href="{% url 'user:public_profile' obj.user.profile.id %}" >{{obj.user}}</a>
        </div>    
        <div></div>
        <div>
            <!-- ACCEPT FRIEND REQUEST -->
            {% if obj.user in rel_sender  and  request.user not in obj.friends.all %}            
        <div class="social_button" style="display: grid; grid-template-columns: 50% 50%;">
            <div>
                <form action="{% url 'user:accept-invitation' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #10a79a; border-color: #6c16b4;"> Accept</button>
                </form>
            </div>
            <div>
                <form action="{% url 'user:reject-invitation' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #9a10a7; border-color: #6c16b4;"> Reject</button>
                </form>
            </div>
        </div>

            {% endif %} 
        </div>
    </div>
    {% endif %}
   
    {% endfor %}
</div>


 <!------------------ 2.  FRIENDS ------------------------>
 <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
 background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
 width: 40%; height: fit-content; margin:5px 30%;">
 <h4>
     <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
     {% if request.user.is_authenticated %}
         <span style="color: gold;">{{request.user.username}}'s</span> Friends

     {% else %}
    
     {% endif %}

     </span>
 </h4>
</div>
 <div class="links_container">
    {% for obj in object_list %}
    {% if request.user in obj.friends.all %} <!-- if friends... -->

    <div class="profile_line_all_profiles">
        <!--PROFILE IMAGE-->
        <div  style="display: inline-block;">
            <img class="social_icon" src="{{obj.image.url}}">
        </div>

        <!--PROFILE NAME AND LINK-->
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a href="{% url 'user:public_profile' obj.user.profile.id %}" >{{obj.user}}</a>
        </div>    

            <!-- REMOVE FROM FRIENDS -->
            {% if request.user in obj.friends.all %} <!-- if friends... -->
            <div class="social_button" style="display: inline-block;">
                <form action="{% url 'user:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    {% if request.user in obj.friends.all %} <!-- if friends... -->
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #a73310; border-color: #6c16b4;"> Remove from friends</button>
                    {% endif %} 
                </form>
            </div>
            {% endif %}
    </div>   
    {% endif %}
    {% endfor %}
</div>


 <!------------------ 3. WAITING FOR APPROVAL ------------------------>
 <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
 background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
 width: 40%; height: fit-content; margin:5px 30%;">
 <h4>
     <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
     {% if request.user.is_authenticated %}
         <span style="color: gold;">{{request.user.username}}'s</span> Friend Requests

     {% else %}
    
     {% endif %}

     </span>
 </h4>
</div>
 <div class="links_container">
    {% for obj in object_list %}
    {% if obj.user in rel_receiver and request.user not in obj.friends.all %} <!-- we have sent user an invitation but not friended yet -->

    <div class="profile_line_all_profiles">
        <!--PROFILE IMAGE-->
        <div  style="display: inline-block;">
            <img class="social_icon" src="{{obj.image.url}}">
        </div>

        <!--PROFILE NAME AND LINK-->
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a href="{% url 'user:public_profile' obj.user.profile.id %}" >{{obj.user}}</a>
        </div>    

        <div>
               <!-- WAITING FOR APPROVAL -->
            {% if obj.user in rel_receiver and request.user not in obj.friends.all %} <!-- we have sent user an invitation but not friended yet -->
            <div class="social_button" style="display: inline-block;">
                <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #106ba7; border-color: #6c16b4;"> Waiting for approval </button>
            </div>
            {% endif %} 

        </div>
    </div>   
    {% endif %}
    {% endfor %}
</div>





 <!------------------ 4 . ADD TO FRIENDS ------------------------>
 <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
 background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
 width: 40%; height: fit-content; margin:5px 30%;">
 <h4>
     <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
     {% if request.user.is_authenticated %}
         <!--<span style="color: gold;">{{request.user.username}}'s</span>--> All Users

     {% else %}
    
     {% endif %}

     </span>
 </h4>
</div>
<div class="links_container">
    {% for obj in object_list %}
    {% if obj.user not in rel_receiver and obj.user not in rel_sender %} <!-- no relationship yet -->

    <div class="profile_line_all_profiles">
        <!--PROFILE IMAGE-->
        <div  style="display: inline-block;">
            <img class="social_icon" src="{{obj.image.url}}">
        </div>

        <!--PROFILE NAME AND LINK-->
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a href="{% url 'user:public_profile' obj.user.profile.id %}" >{{obj.user}}</a>
        </div>    

        <div>
            <!-- ADD TO FRIENDS -->
            <div class="social_button" style="display: inline-block;">
                <form action="{% url 'user:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %} <!-- no relationship yet -->
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #10a761; border-color: #6c16b4;">  Add to Friends </button>
                    {% endif %} 
                </form>
            </div>

        </div>
    </div>   
    {% endif %}
    {% endfor %}
</div>






<br>

<!--
<div class="links_container">
    {% for obj in object_list %}
    <div class="profile_line_all_profiles">
        <!--PROFILE IMAGE--
        <div  style="display: inline-block;">
            <img class="social_icon" src="{{obj.image.url}}">
        </div>

        <!--PROFILE NAME AND LINK--
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a href="{% url 'user:public_profile' obj.user.profile.id %}" >{{obj.user}}</a>
        </div>    

        <div>
            <!-- ADD TO FRIENDS --
            {% if obj.user not in rel_receiver and obj.user not in rel_sender %} <!-- no relationship yet --
            <div class="social_button" style="display: inline-block;">
                <form action="{% url 'user:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %} <!-- no relationship yet --
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #10a761; border-color: #6c16b4;">  Add to Friends </button>
                    {% endif %} 
                </form>
            </div>
            {% endif %}

            <!-- WAITING FOR APPROVAL --
            {% if obj.user in rel_receiver and request.user not in obj.friends.all %} <!-- we have sent user an invitation but not friended yet --
            <div class="social_button" style="display: inline-block;">
                <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #106ba7; border-color: #6c16b4;"> Waiting for approval </button>
            </div>
            {% endif %} 

            <!-- REMOVE FROM FRIENDS --
            {% if request.user in obj.friends.all %} <!-- if friends... --
            <div class="social_button" style="display: inline-block;">
                <form action="{% url 'user:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    {% if request.user in obj.friends.all %} <!-- if friends... --
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #a73310; border-color: #6c16b4;"> Remove from friends</button>
                    {% endif %} 
                </form>
            </div>
            {% endif %} 


            <!-- ACCEPT FRIEND REQUEST --
            {% if obj.user in rel_sender  and  request.user not in obj.friends.all %}            
            <div class="social_button" style="display: inline-block;">
                <form action="{% url 'user:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class = "btn btn-info" style="font-size: medium ;background-color: #10a79a; border-color: #6c16b4;"> Accept request</button>
                </form>
            </div>
            {% endif %} 
        </div>
    </div>   
    {% endfor %}
</div> -->


  {% endblock body %}

templates/friends_invites.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="">
    <br>
    <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
        background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
        width: 60%; height: fit-content; margin:5px 15%;">
        <h4>
            <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
            {% if request.user.is_authenticated %}
                <span style="color: gold;">{{request.user.username}}'s</span> Friends

            {% else %}
           
            {% endif %}

            </span>
        </h4>
    </div>


<div class="links_container">
    {% for friend in profile.friends.all %}
    <div class="profile_line">
        <div  style="display: inline-block;">
            {% if friend.profile.image == "default.jpg" %}
            <img class="social_icon" src="/media/profile_pics/{{friend.profile.image}}">
            {% else %}
            <img class="social_icon" src="/media/{{friend.profile.image}}">
            {% endif %}
        </div>
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a  href="{% url 'user:public_profile' friend.profile.id %}" >{{friend}}</a>
        </div>    
    </div>   
    {% endfor %}
</div>


<!--<a class="btn btn-primary" style="margin-top: 30px;background-color: #106aa7; 
border-color: #6c16b4; margin-left: 40%;" href="{% url 'user:update_profile'  profile.id %}" role="button">Update Profile</a>
-->


<div class="">
    <br>
    <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
        background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
        width: 60%; height: fit-content; margin:5px 15%;">
        <h4>
            <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
            {% if request.user.is_authenticated %}
                <span style="color: gold;">{{request.user.username}}'s</span> Friends Requests
            {% else %}
            {% endif %}
            </span>
        </h4>
</div>


{% if is_empty %}
<h1 style="color: white;"></h1>
{% endif %}

<div class="links_container">
    {% for item in qs %}
    <div class="profile_line">
        <div  style="display: inline-block;">
            {% if item.profile.image == "default.jpg" %}
            <img class="social_icon" src="/media/profile_pics/{{item.image}}">
            {% else %}
            <img class="social_icon" src="/media/{{item.image}}">
            {% endif %}
        </div>
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a  href="{% url 'user:public_profile' item.id %}" >{{item.user.username}}</a>
        </div>    
    </div>   
    {% endfor %}
</div>


<br><br><br>



  {% endblock body %}

templates/inviteprofiles.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}


<div class="">
    <br>
    <div class="jumbotron text-center " style="color: mintcream ; border-radius: 10px; padding: 10px;
        background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
        width: 60%; height: fit-content; margin:5px 15%;">
        <h4>
            <span style="text-transform: capitalize; letter-spacing: 2px; font-style: italic; font-size: 25px; ">
            Users to Invite

            </span>
 
        </h4>
    </div>




<div class="links_container">
    {% for item in qs %}
    <div class="profile_line">
        <div  style="display: inline-block;">
            {% if item.user.profile.image == "default.jpg" %}
            <img class="social_icon" src="/media/profile_pics/{{item.user.profile.image}}">
            {% else %}
            <img class="social_icon" src="/media/{{item.user.profile.image}}">
            {% endif %}
        </div>
        <div class="social-id-display" style="display: inline-block;   align-self: center;">
            <a  href="{% url 'user:public_profile' item.user.profile.id %}" >{{item.user}}</a>
        </div>    
    </div>   
    {% endfor %}
</div>


<br><br><br>



  {% endblock body %}

templates/layout.html
<!DOCTYPE html>

{% load static %}
{% load crispy_forms_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.1.1/dist/chart.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/analyze.css">
    <link rel="stylesheet" type="text/css" href="/static/css/grid.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    <link rel="stylesheet" href="/static/css/animate.min.css">

    <title>Shambala's Gates</title>

</head>
<body>
{% include "includes/navbar.html" %}

{% block body %}


{% endblock body %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@next/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@next/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-waypoints@2.0.5/waypoints.min.js"></script>
<script src="/static/js/jquery.waypoints.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
<script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//cdn.jsdelivr.net/selectivizr/1.0.3b/selectivizr.min.js"></script>

<!--type="text/javascript"-->

<script src="/static/js/animations.js"></script>
<script src="/static/js/carousel.js"></script>
<script src="/static/js/copytext.js"></script>

</body>


</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        
        <div style="padding: 30px; border-radius: 30px; 
        margin-top: 30px; background-size: cover;
        background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg);">

        <h3 style="color: white;">LOGIN</h3>
        <form method = "post" style="color: white;">
            {% csrf_token %}
            
            {{form|crispy}}
            <!--{{form.as_p}}-->
            <button type = "submit" class = "btn btn-danger" 
            style="background-color: #7e19d1 !important; float: right; border-color: #c691f2" >Login </button>

            <br><br>
        </form>
        </div>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        
        <div style="padding: 30px; border-radius: 30px; 
        margin-top: 30px; background-size: cover;
        background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg);">

        <h3 style="color: white;">REGISTER</h3>
        <form method = "post" style="color: white;">
            {% csrf_token %}
            
            {{form|crispy}}
            <button type = "submit" class = "btn btn-danger" 
            style="background-color: #7e19d1 !important; float: right; border-color: #c691f2" >Register </button>

            <br><br>
        </form>
        </div>
    </div>
  </div>

{% endblock body %}

templates/todos.html
{% extends "layout.html" %}

{% block body %}


<form class="todo-wrapper" method="POST">
    {% csrf_token %}
    <div class="todo-card" style="background-color: #6c15b3">
        <div>
            <p class="todo-text">Todo</p> 
        </div>
        <div>
            <input class="todo-box" maxlength="50"size="50" type="text" style="background-color: #470e76;" name="title" id="title" placeholder="Enter to-do" required  >
        </div>
    </div>
    <!--<a class = "btn btn-danger" href = "{% url 'todo:addtodo' %}">Add Todo </a>-->
    <button type = "submit" class = "btn btn-info" style="margin-top: 10px; height: 60px ;background-color: #106aa7; border-color: #6c16b4;">Submit</button>
</form>

<hr>

{% if messages %}
{% for message in messages %}
<br>
<div style="color: mintcream ; border-radius: 10px; padding: 10px;
background-image: linear-gradient(#170227d7, #470e76ef), url(/static/purple\ background\ login\ pae.jpg); 
width: 40%; margin:5px 30%; text-align: center;border-color:#470e76ef" class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}

{% if todo_list %}
    <div class="line">
        <div>Title</div>
        <div>Date</div>
        <div>Update</div>
        <div>Delete</div>
    </div>   
        {% for todo in todo_list %}
    <div class="line">
        <div class="hover" id="{{todo.id}}"  onclick="copyToClipboard('#{{todo.id}}')">{{todo.title}}</div>
        

        <!--<div>{{todo.author.username}}</div>-->
        <div>{{todo.created_date}}</div>
        <div><a href="{% url 'todo:updatetodo' todo.id %}" class = "btn btn-info btn-sm">Update</a></div>
        <div><a href="{% url 'todo:deletetodo' todo.id %}" class = "btn btn-info  btn-sm">Delete</a></div>
    </div>   
        {% endfor %}


{% else %}

{% endif %}
<style type="text/css">
    .hover:hover {
        text-decoration: underline;
        text-underline-offset: 5px;
        transition: border 0.4s, color 0.4s;
    }

    .hover {
        transition: text-decoration 0.5s;
    }

</style>
{% endblock body %}

templates/updateimage.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="profile_container">
    <div class="profile_left_container" >
        <img style="width: 150px; height: 150px;" class="rounded-circle account-img" src="{{user.profile.image.url}}">
        <span style="text-transform: capitalize; place-self: center; letter-spacing: 4px; font-style: italic; font-size: 25px; color: gold; font-weight: 700;">{{user.username}}</span>
    </div>
    <div class="profile_right_container1 ">
        <div class="social_input add_interests" >
            <form method="POST" enctype="multipart/form-data">
                <div>   
                    {% csrf_token %}
                    {{forms.Image_form|crispy}}

                    <!--<input type="text" name="interests" required id="id_interests">-->
                </div>
                <div class="social_button">
                    <button type = "submit" class = "btn btn-info btn-sm">Update Image</button>
                </div>
            </form>
        </div>   
    </div>   
</div>










  {% endblock body %}

templates/updatetodo.html
{% extends "todos.html" %}